### PR TITLE
[WIP] Add a sphinx API documentation

### PR DESCRIPTION
**Pull request by jbarnoud**
See #81 

This pull request setup sphinx to document the API. Sphinx is setup to render a reference documentation using the docstrings. The docstring are formated using the [numpy format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). So far we were making an error regarding this format: the keyword to list the exceptions raised by a function is `Raises` rather than `Exceptions`.

The pull request adds docstrings in several `__init__.py` files. This could conflict with the cleaning @HubLot is doing with optional dependencies. 

In order to build the doc, run `make html` in the `doc-api` directory; then open `doc-api/build/html/index.html`. Sphinx and [napoleon](https://pypi.python.org/pypi/sphinxcontrib-napoleon) are required to build the doc; see the `dev_requirements.txt` file.

### CODE REVIEW

**Comment by HubLot** [comment]
:+1:

**Comment by jbarnoud** [comment]
Here is a demo, because building the doc is not trivial. http://jbarnoud.github.io/PBxplore/index.html

**Comment by pierrepo** [comment]
@jbarnoud and @HubLot thanks for your efforts.
If I understood correctly, we have two choices for the documentation:

1. We use Sphinx and we have to build ourselve the documentation based on doctrings. The doc is then available on GitHub

2. We use readthedoc that automatically build the documentation after every commit as a CI. The doc is then available in the readthedoc website.

Option 2 seems easier to me. No? I can quickly create an account at readthedoc if needed.  @jbarnoud you can hate me ;-) 
Let me know what you think about that.

**Comment by jbarnoud** [comment]
@pierrepo That's pretty much it. There is a third option that is pythonhosted.org which comes with pipy. But I do not know how it works.

> We use Sphinx and we have to build ourselve the documentation based on doctrings. The doc is then available on GitHub

It should be possible to have the doc built by Travis and pushed to the main repo gh-pages branch. This way, it is fully automated. Yet, it is not the most trivial way. It could be the best option, though, as building the doc requires several external tools due to the inclusion of notebooks.

> We use readthedoc that automatically build the documentation after every commit as a CI. The doc is then available in the readthedoc website.

This would be the simpler option, assuming we can have readthedocs build the doc. As I said above, the build requires a bunch of tools (jupyter and pandoc mostly), and these tools may not be available in the context of readthedoc.

> Option 2 seems easier to me. No? I can quickly create an account at readthedoc if needed.

I will try to have readthedoc build our doc on my fork. If I manage to do it, then I'll explain how I did it.

> @jbarnoud you can hate me ;-) 

Do you really want me to hate you? :stuck_out_tongue_winking_eye:

**Comment by jbarnoud** [comment]
@pierrepo Readthedocs is a viable option. I managed to have it build the doc dispite the apparently complicated building process : <http://jbarnoudpbxplore.readthedocs.org>. I have a lot of cleaning to do, though.

By the way, I added a notebook about writing PB sequences in files. It lead to #85. http://jbarnoudpbxplore.readthedocs.org/en/latest/notebooks/WritePB.html

**Comment by pierrepo** [comment]
OK nice!
I will open an account at readthedoc.
Which tutorial did you follow to setup your account?
For me, we need to kind of documentation:
- code documentation extracted from source files
- tutorial / how-to documentation extracted from ipython notebooks

Sounds good to you too?

**Comment by jbarnoud** [comment]
I followed no tutorial. I just created an account, connected it to my 
github one, activated the repo in the readthedocs interface, and touched 
all the buttons until it worked :P

More seriously, the 3 first steps are required and should be trivial. 
Then some settings in the advanced settings are necessary:

* Requirements file must be set to doc_requirements.txt
* Python configuration file can be blank
* Default branch must be the branch you want the doc to be build 
against, I would strongly advice to try with an other branch that master 
at first
* The PDF version does not work and must be deactivated, I do not know 
for the epub version
* The option " Give the virtual environment access to the global 
site-packages dir." must be selected

Once the settings changed, do not forget to click "submit" (it became so 
frequent that settings get saved as you change them that I did not even 
notice the submit button).

Note that the build process is heavily customized and therefore most 
likely do not look like the tutorials. For instance, the build 
workaround  a [bug in 
nbconvert/pandoc](https://github.com/jupyter/nbconvert/issues/97), and 
it adds a header in the notebooks with the table of content and links to 
other versions of the notebook.

**Comment by pierrepo** [comment]
Thanks.
Why not directly plug readthedoc to the master branch? I least we will see the mess from the beginning and will improve it PR after PR.

Do we still need the Sphinx doc?

**Comment by jbarnoud** [comment]
The doc on readthedocs is the sphinx doc. So yes we still need it :)

I think we should start on a different branch because master should never be broken, yet the doc still requires some cleanups that could lead to a break. The history of my sphinx branch is super messy so I could even do a rebase to clean it, and master should never go through a rebase.

**Comment by pierrepo** [comment]
Thanks.
Why not directly plug readthedoc to the master branch? I least we will see the mess from the beginning and will improve it PR after PR.

Do we still need the Sphinx doc?

**Comment by jbarnoud** [comment]
I am fighting with ReadTheDocs that fails with weblogo because of font issues in ghostscript. Once this issue solved, I will clean my history, and the branch will be ready to merge. Then @pierrepo can set ReadTheDocs on master as there should not be drastic changes anymore.

**Comment by jbarnoud** [comment]
Argh. @pierrepo you are quick to merge! Not long ago the pull request was full of crocodiles, hence the work-in-progress label. Thankfully this one was just fixed.

Tomorrow I'll update the pull request message to document few things to know about how the doc works.

**Comment by jbarnoud** [comment]
I updated the pull request message to document the pull request, even so it is merged already. I also linked issues on things I need to finish.

**Comment by pierrepo** [comment]
Oups. Sorry @jbarnoud. I misread your messages and thought I had to quickly merge your PR :-(
Let me know when you're ready.

**Pull request merged**
