### PR TITLE
conda package

### PR DESCRIPTION
**Pull request by HubLot**
Hi,

This a first step to create a conda package for pbxplore.

#### Meta.yaml
The main file is the `meta.yaml` one which describes how to build and test pbxplore for conda. 
So far, the version number is set manually and the build against the master on github. 
An improvement will be to generate the version number (to be synced with the pypi) and build the package against a tag ( with the `git_tag` instead of `git_branch`).

#### How to build?

- `conda build --python 2.7 -c bioconda -c mdanalysis pbxplore` (assuming you're in the `conda_build` directory)
- This should create a tar.bz2 and conda give you the path at the end of the process.
- Generate a package for all platforms : `conda convert --platform all /path/to/archive/pbxplore-1.3.1-py27_0.tar.bz2` (this will generate archive for linux 32/64b, windows 32/64b and osx 64b)

#### How to upload?
 - First, create an account on https://anaconda.org/ and login through the `anaconda login` command.
 - `anaconda upload /path/to/archive/pbxplore-1.3.1-py27_0.tar.bz2`
 - do this for all archives generated

I give it a try and upload a version with python 2.7 : https://anaconda.org/Hub_lot/pbxplore
I will remove it once @pierrepo have done it to avoid confusion

So far, I managed to build conda package for python 2.7 only. I have a weird error when I try a different version of python (`--python 3.4` for example). Maybe one of you can try.

#### TODO list
- [ ] Automatically update the version and git_tag value when uploading a new version (with a script)
- [x] Figure out how to build against another version of python. 
- [x] At some point, a "How to release" file will be great to remember the different steps for pypi, conda and the docs

### CODE REVIEW

**Comment by pierrepo** [comment]
For version number update, bumpversion [1] should do the trick (thanks to Benoist Laurent).

[1] https://pypi.python.org/pypi/bumpversion

**Comment by HubLot** [comment]
Here, the PR for conda. 
I managed to build conda package for all versions of Python (2.7 to 3.5).
The main job is to generate the package for the good version of python then generate packages for all plateforms.
For Bumpversion, I'll try it and make a new PR.

**Comment by HubLot** [comment]
@pierrepo did you manage to create anaconda packages and upload them to the website?

**Comment by pierrepo** [comment]
Not yet. I have to install anaconda first ;-)

**Pull request merged**
