### PR TITLE
Update PBassign version

### PR DESCRIPTION
**Pull request by pierrepo**
We can get access to PBxplore version with the command:

    PBassign -v

### CODE REVIEW

**Comment by pierrepo** [comment]
@HubLot can you have a look please ?

**Comment by HubLot** [comment]
Great, good catch!

I will add also to the others tools

**Comment by HubLot** [comment]
Ok for you @pierrepo ? Ready to merge?

**Comment by pierrepo** [comment]
Almost. Can you also please update the documentation? We used to output the result of ``PBtool -h`` in doc. See for instance:
https://pbxplore.readthedocs.io/en/latest/PBassign.html#

**Comment by HubLot** [comment]
indeed, it's done

**Comment by pierrepo** [comment]
ok thanks!

**Pull request merged**
