### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by HubLot**
a few improvements for PEP8

### CODE REVIEW

**Comment by jbarnoud** [comment]
:+1:

**Comment by pierrepo** [comment]
Thanks of the house cleaning ;-)

**Comment by HubLot** [comment]
The highlights lines in my editor started to annoy me :)

**Comment by pierrepo** [comment]
PEP8-fanatic ;-)

**Comment by pierrepo** [comment]
Which editor by the way?

**Comment by HubLot** [comment]
Sublime Text 3 + Anaconda package + GitGutter, great combo :)

**Comment by jbarnoud** [comment]
On 29/09/15 17:48, Hub wrote:
>
> Sublime Text 3 + Anaconda package + GitGutter, great combo :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/pull/79#issuecomment-144099842>.
>
Is it the place to start a troll about editors? Because Vim is clearly 
better! (Sorry, could not help it)

**Comment by pierrepo** [comment]
Sure it is the place.
So @HubLot dit you pay for the Sublime Text license or are you still hitting that "register later" button every two days?
And @HubLot why Anaconda on Linux? 
Personally, I prefer geany. It has no idea what is PEP8.

**Comment by HubLot** [comment]
I could have bet on the response of @jbarnoud !
@pierrepo, no I hit this button every day. But the more I us it, the more I think to buy it.
When i said Anaconda, I was speaking about the sublime text package 'Anaconda' (which is bundle for python development) , not the python distribution.
I never used geany...

**Comment by pierrepo** [comment]
Thanks for your interesting comments guys.
Thanks also for the nice work done so far!

**Pull request merged**
