### PR TITLE
Remove --flat option

### LINKED ISSUE #117: Remove --flat option
Add in documentation one way to flatten fasta file.
For instance:
cat toto.PB.fasta | sed "s/^>.*/\t/" | tr -d "\n" | tr "\t" "\n"

Remove all related unit tests and test files.

### PR DESCRIPTION
**Pull request by pierrepo**
Fix #117

### CODE REVIEW

**Comment by pierrepo** [comment]
@HubLot / @jbarnoud can you please review this PR?
Hopefully I did not break everything ;-)

**Comment by HubLot** [comment]
looks good to me!

**Comment by jbarnoud** [comment]
There is one notebook to adapt. The one about writing PB sequences.

**Comment by pierrepo** [comment]
Thank you very much @jbarnoud. I changed `WritePDB.ipynb` accordingly.

**Pull request merged**
