### PR TITLE
Add Zenodo badge

### PR DESCRIPTION
**Pull request by pierrepo**
DOI is the 'generic' one that cover all PBxplore versions.

### CODE REVIEW

**Review by HubLot — APPROVED** [review]
good. Not sure why I was assigned :)

**Comment by pierrepo** [comment]
@HubLot 
> Not sure why I was assigned :)

Order of appearance... ;-) 
image

**Comment by HubLot** [comment]
Yes but it was in "Assignees" not "Reviewers"  :zany_face:
anyway!

**Comment by pierrepo** [comment]
Oups....

**Pull request merged**
