### PR TITLE
Remove --phipsi option

### PR DESCRIPTION
**Pull request by HubLot**
Fix the issue #118 

I didn't remove `write_phipsi` and `write_phipsi_entry` function because they can be useful for the API user.
I update the notebook to warn about the RAM issue and suggest an alternative.

Please check if I didn't miss a thing.

### CODE REVIEW

**Comment by pierrepo** [comment]
I would also remove both `write_phipsi` and `write_phipsi_entry` functions that are mostly subjectif formatting functons and rather provide a more *free* example in the Notebook file. For instance:

```python
pdb_path = os.path.join(pbx.DEMO_DATA_PATH, '2LFU.pdb')

with open('output.phipsi', 'w') as outfile:
    for chain_name, chain in pbx.chains_from_files([pdb_path]):
        dihedral = chain.get_phi_psi_angles()
        for res in sorted(dihedral):
            print("{} {:6d} {} {} ".format(chain_name, res, dihedral[res]["phi"], dihedral[res]["psi"]))
```

**Comment by HubLot** [comment]
Done!

**Comment by pierrepo** [comment]
Wunderbar !

**Comment by pierrepo** [comment]
Fix #118

**Comment by HubLot** [comment]
maybe after these 2 PR, it is worth it to push a new version on Pypi?

**Comment by pierrepo** [comment]
Yep. Correct. I'll do it today.

**Comment by jbarnoud** [comment]
We should have a CHANGELOG somewhere to write down what changes between two versions.

**Comment by pierrepo** [comment]
Brilliant idea.
I'll start.

**Pull request merged**
