### PR TITLE
Update CI badges

### LINKED ISSUE #178: Update badge for CI
We are now using GitHub actions for CI (instead of Travis previously).

The Travis CI badge is no longer relevant. @HubLot could you try to update it with [a workflow badge](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge)?

### PR DESCRIPTION
**Pull request by HubLot**
fix #178

### CODE REVIEW

**Comment by pierrepo** [comment]
To avoid confusion with ReadTheDocs badge, could you rename workflows `PBxplore test code` and `PBxplore test doc` or simply `test code` and `test doc` ?

**Comment by HubLot** [comment]
I can rename test and doc as "build" and "build doc". Sounds better than "test"

**Comment by pierrepo** [comment]
Actually the issue is with the ReadTheDocs badge "doc passing" that is not very explicit...
So maybe : "GitHub CI code" and "Github CI doc"?

**Comment by HubLot** [comment]
Okay!

**Comment by pierrepo** [comment]
Many thanks @HubLot  :clap:

**Comment by HubLot** [comment]
docs is failing now:
image

image

**Comment by pierrepo** [comment]
I'm on it...

**Comment by pierrepo** [comment]
:tada:

image

**Comment by HubLot** [comment]
it's beautiful

**Pull request merged**
