### PR TITLE
Add a progress bar during PB assignment of a trajectory (#150)

### PR DESCRIPTION
**Pull request by HubLot**
This progress bar will always print the first frame and one every 100.
One every 100 frames seems a good ratio between number of print statements (to avoid a lot unnecessary prints) and time between 2 of them (to avoid a too long time of wait). 
It is better than one every 50 ;)

The print statements is on stderr.

### CODE REVIEW

**Comment by pierrepo** [comment]
Nice work.
Could you also print the total frame number at the end?
Do you think we could also move the printing of chains read for PDB/PDBX files into `loader.py`?

**Comment by HubLot** [comment]
> Could you also print the total frame number at the end?

What do you mean ? The total frame number is already print each time (`Frame 100/1000` where 1000 is the number of frames). You mean print the last frame like (`Frame 1000/1000`) ?

> Do you think we could also move the printing of chains read for PDB/PDBX files into `loader.py`?

Yes, we could. It will be more consistent (instead of a print inside a method)

**Comment by pierrepo** [comment]
>     Could you also print the total frame number at the end?
> 
> What do you mean ? The total frame number is already print each time (Frame 100/1000 where 1000 is the number of frames). You mean print the last frame like (Frame 1000/1000) ?

Yes, the very last frame like `frame 1000/1000` whether or not the total number of frame is a multiple of 100. For instance, `frame 250/250` or `frame 153/153` should work too.

>     Do you think we could also move the printing of chains read for PDB/PDBX files into loader.py?
> 
> Yes, we could. It will be more consistent (instead of a print inside a method)

Awesome. Could you do it within the same PR?
As an extra bonus, it will also allow to get the number of chains for PDBx structure files (not implemented in the current version).

**Comment by HubLot** [comment]
Okay I'll look into those!

**Comment by HubLot** [comment]
For the trajectory, I re-arrange a little bit the progress bar to print the first frame, one every 100 and the last one.

For PDB/PDBx, I create a property to get the number of chains and move the print statement into the `chains_from_files` function

**Comment by pierrepo** [comment]
Cool. Thanks @HubLot !

**Pull request merged**
