### PR TITLE
Improve drawing of PBs map

### LINKED ISSUE #146: PBstat with `--map` option crash when the number of residus is < 20
With a PB count file with less than 20 residus, the map generation is failing :

```bash
$ PBstat -f 19residus.count -o 19residus --map
Index of first residue is: 1
Traceback (most recent call last):
  File "pbxplore/bin/PBstat", line 9, in <module>
    load_entry_point('pbxplore', 'console_scripts', 'PBstat')()
  File "pbxplore/scripts/PBstat.py", line 173, in pbstat_cli
    pbx.analysis.plot_map(file_fig_name, count, residue_min, residue_max)
  File "pbxplore/analysis/visualization.py", line 168, in plot_map
    fig.text(0.01 + text_shift * 2, 0.5, "PBs", rotation=90, weight="bold",
UnboundLocalError: local variable 'text_shift' referenced before assignment
```

### PR DESCRIPTION
**Pull request by pierrepo**
Fix #146 
@HubLot could you test please?

### CODE REVIEW

**Comment by HubLot** [comment]
Looks good to me! The use of different axes is clever.
I tried on several size of proteins (up to 360 residus) and the results looks always readable. Good job!

Can you check the checkbox 'allow edits from maintainers' @pierrepo? I would like to test this feature and fix some PEP8 issues :)

**Comment by pierrepo** [comment]
Thanks!
I don't have this option. Maybe because it's not a fork?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by HubLot** [comment]
Oh indeed. Should I push a commit directly in this PR then? Dunno if it's the right thing to do

**Comment by pierrepo** [comment]
Yes go ahead. 

Le 17 janvier 2017 15:50:13 GMT+01:00, Hub <notifications@github.com> a écrit :
>Oh indeed. Should I push a commit directly in this PR then? Dunno if
>it's the right thing to do
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pierrepo/PBxplore/pull/147#issuecomment-273188961

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Pull request merged**
